#!/bin/sh

# vim
ln -sf ~/dotfiles/.vimrc ~/
mkdir -p ~/.vim/tmp/swap
mkdir -p ~/.vim/tmp/backup
mkdir -p ~/.vim/tmp/undo
ln -sf ~/dotfiles/coc-settings.json ~/.vim/

# neovim
mkdir -p ~/.config/nvim
ln -sf ~/dotfiles/nvim/init.vim ~/.config/nvim/
ln -sf ~/dotfiles/nvim/coc-settings.json ~/.config/nvim/

# emacs
mkdir -p ~/.config/doom
ln -sf ~/dotfiles/doom/config.el ~/.config/doom/
ln -sf ~/dotfiles/doom/init.el ~/.config/doom/
ln -sf ~/dotfiles/doom/packages.el ~/.config/doom/

# zsh
ln -sf ~/dotfiles/debian/.zshenv ~/
ln -sf ~/dotfiles/debian/.zshrc ~/

# tmux
ln -sf ~/dotfiles/.tmux.conf ~/

#clojure
mkdir -p ~/.config/clj-kondo
ln -sf ~/dotfiles/clojure/clj-kondo/config.edn ~/.config/clj-kondo/
ln -sf ~/dotfiles/clojure/clj-kondo/extra-config.edn ~/.config/clj-kondo/
